name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
      - feature/update-2

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY_APP: laravel-app-repo
  ECS_SERVICE: laravel-app-service
  ECS_CLUSTER: laravel-app-cluster
  CONTAINER_NAME_APP: laravel-app-container

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Laravel App to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create ECR repository if not exists
      run: |
        echo "Ensuring ECR repository for Laravel exists..."
        aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY_APP }} || \
        aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY_APP }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Laravel app image to ECR
      id: build-laravel-image
      run: |
        echo "Building Docker image for Laravel app..."
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:${{ github.sha }} .
        echo "Pushing Docker image to ECR..."
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:${{ github.sha }}

    - name: Create ECS Task Definition
      id: create-task-def
      run: |
        echo "Creating ECS task definition JSON file..."
        cat <<EOF > task-def.json
        {
          "family": "${{ env.ECS_SERVICE }}",
          "containerDefinitions": [
            {
              "name": "${{ env.CONTAINER_NAME_APP }}",
              "image": "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_APP }}:${{ github.sha }}",
              "memory": 512,
              "cpu": 256,
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 80,
                  "hostPort": 80
                }
              ],
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/${{ env.ECS_SERVICE }}",
                  "awslogs-region": "${{ env.AWS_REGION }}",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ]
        }
        EOF

    - name: Ensure ECS Service exists
      run: |
        echo "Checking if ECS service exists..."
        if ! aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query "services[?status=='ACTIVE'] | length(@)" | grep -q 1; then
          echo "Service does not exist. Creating ECS service..."
          aws ecs create-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service-name ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.ECS_SERVICE }} \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-xxxxxxxx],securityGroups=[sg-xxxxxxxx],assignPublicIp=ENABLED}"
        fi

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-def.json
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
